{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  defaultBackend:
    service:
      name: {{ include "chart.fullname" . }}
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
      - {{ include "chart.fullname" . }}
{{- end }}