# # This workflow is intended to deploy previews for the `main` branch and any branch with an open PR targeting it
# # I stubbed this out as it separates the branch deploy step and allows it to be run for any branch in an ad hoc manner
# # this is nice functionality but makes things a bit more complicated
# name: Deploy Branch

# on:
#   workflow_run:
#     workflows: ["Test Build Scan"]
#     types:
#       - completed
#   workflow_dispatch:

# # The GITHUB_SHA is different between a push event and pull_request event
# # The simple branch name is the HEAD ref for pull_request events but REF_NAME for pushes
# env:
#   BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
#   LATEST_SHA: ${{ github.event.workflow_run.head_sha }}

# jobs:
#   deploy-branch:
#     runs-on: ubuntu-latest
#     # Workflow events come through as completed even if a step fails
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     steps:
#       - uses: actions/checkout@v4
#       - id: get_short_sha
#         run: echo "short_sha=$(git rev-parse --short ${{ env.LATEST_SHA }})" >> $GITHUB_OUTPUT
#       - name: Connect to Tailscale
#         uses: tailscale/github-action@v2
#         with:
#           oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
#           oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
#           tags: tag:ci
#       - name: Install Kube Config and Helm
#         run: |
#           mkdir $HOME/.kube
#           echo ${{ secrets.TS_K8S_CONFIG }} | base64 -d > $HOME/.kube/config
#           curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
#       - name: Deploy Branch
#         run: helm upgrade --install app-${{ env.BRANCH_NAME }} --set image.tag=${{ steps.get_short_sha.outputs.short_sha }} ./chart
