name: Deploy Preview Demo
on:
  workflow_dispatch:

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: alexgqq/preview-deploy-example-app:latest
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Install Kube Config and Helm
        run: |
          mkdir $HOME/.kube
          echo ${{ secrets.TS_K8S_CONFIG }} | base64 -d > $HOME/.kube/config
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Deploy Preview
        run: helm upgrade --install example-app ./chart
