name: Deploy Preview Workflow
on:
  workflow_dispatch:

jobs:
  get-short-sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get_short_sha.outputs.short_sha }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - id: get_short_sha
        run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - name: Run Tests
        run: make test

  build-image:
    runs-on: ubuntu-latest
    needs: get-short-sha
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: alexgqq/preview-deploy-example-app:${{ needs.get-short-sha.outputs.short_sha }}
          build-args: |
            PROJECT_VERSION=0.0.1
            COMMIT_SHA=${{ github.sha }}

  deploy-preview:
    needs: [get-short-sha, build-image]
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Install Kube Config and Helm
        run: |
          mkdir $HOME/.kube
          echo ${{ secrets.TS_K8S_CONFIG }} | base64 -d > $HOME/.kube/config
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Deploy Preview
        run: helm upgrade --install example-app --set image.tag=${{ needs.get-short-sha.outputs.short_sha }} ./chart
