name: Test Build Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# The GITHUB_SHA is different between a push event and pull_request event
env:
  LATEST_SHA: ${{ github.ref == 'refs/heads/main' && github.sha || github.event.pull_request.head.sha }}
  IMAGE_NAME: alexgqq/preview-deploy-example-app

jobs:
  test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Tests
        run: make test
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./app/...
      # The image build doesn't depend on the tests to start but we do
      # want to end the workflow sooner if they fail
      # https://github.com/orgs/community/discussions/38361
      # - if: "failure()"
      #   uses: "andymckay/cancel-action@0.3"
      # Error: Resource not accessible by integration

  build-scan-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get_short_sha
        run: echo "short_sha=$(git rev-parse --short ${{ env.LATEST_SHA }})" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and load into the docker engine so we can scan it
      # then push it later to avoid multiple builds
      - name: Build Preview Image
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.get_short_sha.outputs.short_sha }}
          build-args: |
            COMMIT_SHA=${{ env.LATEST_SHA }}
      - name: Run Image Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ steps.get_short_sha.outputs.short_sha }}
          format: 'table'
          # TODO: Leave this for testing
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Push to Container Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.get_short_sha.outputs.short_sha }}
          build-args: |
            COMMIT_SHA=${{ env.LATEST_SHA }}
