name: Test Build Deploy Branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# The GITHUB_SHA is different between a push event and pull_request event
# The simple branch name is the HEAD ref for pull_request events but REF_NAME for pushes
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  LATEST_SHA: ${{ github.ref == 'refs/heads/main' && github.sha || github.event.pull_request.head.sha }}
  IMAGE_NAME: alexgqq/preview-deploy-example-app

jobs:
  test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run Tests
        run: make test
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./app/...
      - name: Run Go Vulnerability Checker
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./app
      # The image build doesn't depend on the tests to start but we do
      # want to end the workflow sooner if they fail
      # https://github.com/orgs/community/discussions/38361
      # - if: "failure()"
      #   uses: "andymckay/cancel-action@0.3"
      # Error: Resource not accessible by integration

  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get_short_sha
        run: echo "short_sha=$(git rev-parse --short ${{ env.LATEST_SHA }})" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and load into the docker engine so we can scan it
      # then push it later to avoid multiple builds
      - name: Build Preview Image
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.get_short_sha.outputs.short_sha }}
          build-args: |
            COMMIT_SHA=${{ env.LATEST_SHA }}
      # To get the vulnerability scan output as a "friendly" markdown table
      # I need to run the trivy cmd directly along with a markdown template file
      # and output it to the summary var
      - name: Image Vulnerability Scan
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.54.1
          trivy image --exit-code 0 --ignore-unfixed \
            --format template --template @.github/markdown.tpl --output report.md \
            --vuln-type os,library --severity CRITICAL,HIGH,MEDIUM \
            ${{ env.IMAGE_NAME }}:${{ steps.get_short_sha.outputs.short_sha }}
          cat report.md >> $GITHUB_STEP_SUMMARY
      - name: Push to Container Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.get_short_sha.outputs.short_sha }}
          build-args: |
            COMMIT_SHA=${{ env.LATEST_SHA }}

  deploy-branch:
    runs-on: ubuntu-latest
    needs: [test-scan, build-push]
    steps:
      - uses: actions/checkout@v4
      - id: get_short_sha
        run: echo "short_sha=$(git rev-parse --short ${{ env.LATEST_SHA }})" >> $GITHUB_OUTPUT
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Install Kube Config and Helm
        run: |
          mkdir $HOME/.kube
          echo ${{ secrets.TS_K8S_CONFIG }} | base64 -d > $HOME/.kube/config
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Deploy Branch
        run: helm upgrade --install app-${{ env.BRANCH_NAME }} --set image.tag=${{ steps.get_short_sha.outputs.short_sha }} ./chart
      - name: Deployment Link Summary
        run: echo "Deployment available at https://app-${{ env.BRANCH_NAME }}.tail80e68.ts.net" >> $GITHUB_STEP_SUMMARY
